# Generated by Django 4.2 on 2023-07-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='event_paricipant',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
