# Generated by Django 4.2 on 2023-07-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_image_alter_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='events/%y'),
        ),
    ]
